name: Environment Variables, Secrets

on:
  workflow_dispatch:

env:
  LOCAL_USER: "Prabhu N"
  ENVIRONMENT: "DevOps Training"

jobs:
  show-env:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ”¹ Print hardcoded env values
        run: |
          echo "ğŸ‘¤ Local User: $LOCAL_USER"
          echo "ğŸŒ Environment: $ENVIRONMENT"
      - name: ğŸ” Print Secrets and Variables
        env:
          USER_FROM_SECRET: ${{ secrets.USER_NAME }}
          PROJECT_FROM_VAR: ${{ vars.PROJECT_NAME }}
        run: |
          echo "ğŸ” Secret User: $USER_FROM_SECRET"
          echo "âš™ï¸ Project: $PROJECT_FROM_VAR"
